# constants_client.py

class CLIENT_LOGS:
    CONNECTED = '[LOG] Connected to server at {server_addr}:{server_port}'
    SENDING_SYN = '[LOG] Sending SYN packet with protocol={protocol}, max_fragment_size={max_fragment_size}, window_size={window_size}...'
    WAIT_SYNACK = '[LOG] Waiting for SYN-ACK from server...'
    RECEIVED_SYNACK = '[LOG] Received SYN-ACK: {syn_ack_data}'
    SENDING_ACK = '[LOG] Sending final ACK packet...'
    HANDSHAKE_SUCCESS = '[LOG] Handshake completed successfully!'
    CONNECTION_ESTABLISHED = '[LOG] Connection established with protocol={protocol}, max_fragment_size={max_fragment_size}, window_size={window_size}'
    MESSAGE_FRAGMENTED = '[LOG] Message fragmented into {num_chunks} chunks of max size {max_fragment_size}'
    SENDING_FRAGMENT = "[LOG] Sending fragment {current}/{total}: '{fragment}' (seq={seq_num})"
    SERVER_ACK = '[LOG] Received ACK from server for fragment {seq_num}'
    SERVER_NACK = '[LOG] Received NACK from server requesting retransmission of fragment {seq_num}'
    MESSAGE_SENT = '[LOG] Message sent successfully in {num_fragments} fragments'
    RECEIVED_ACK = '[LOG] Received ACK for sequence {ack_seq}'
    WINDOW_MOVED = '[WINDOW] Window moved: [{old_base}-{old_end}] → [{new_base}-{new_end}]'
    RECEIVED_NACK = '[LOG] Received NACK for sequence {nack_seq}'
    RESENDING_PACKET = '[LOG] Resending packet {seq}'
    INIT_DISCONNECT = '[LOG] Initiating disconnection...'
    WAIT_DISCONNECT_ACK = '[LOG] Waiting for server ACK...'
    SERVER_DISCONNECT_ACK = '[LOG] Recieved server ACK disconnect. Closing socket...'
    DISCONNECTED = '[LOG] Disconnected successfully.'
    WINDOW_SR = '[WINDOW] SR Window: [{window_start}-{window_end}]'
    WINDOW_ACKED = '[WINDOW] Acked packets: {acked_in_window}'
    WINDOW_WAITING_ACK = '[WINDOW] Waiting for ACK: {unacked}'
    TIMEOUT_RESEND = '[LOG] Timeout detected: Resending packets from {base_seq_num} to {next_seq_num_minus1} (Attempt {retry_count}/{max_retries})'

class CLIENT_ERRORS:
    NO_RESPONSE = '[ERROR] No response from server'
    INVALID_RESPONSE = '[ERROR] Invalid response from server'
    HANDSHAKE_FAILED = '[ERROR] Handshake failed: {message}'
    FAILED_CONNECT = '[ERROR] Failed to connect: {error}'
    MAX_RETRIES = '[ERROR] Maximum retries ({max_retries}) exceeded. Message delivery failed.'
    UNEXPECTED_RESPONSE = '[ERROR] Unexpected response from server: {parsed}'
    FAILED_SEND = '[ERROR] Failed to send message: {error}'
    INVALID_INPUT = '[ERROR] Invalid input. Values must be numbers.'
    MESSAGE_EMPTY = '[ERROR] Message cannot be empty.'
    FAILED_DISCONNECT = '[ERROR] Failed to disconnect: {error}'
    ERROR_RECEIVING_ACK = '[ERROR] Error receiving ACK: {error}'
